apiVersion: batch/v1
kind: CronJob
metadata:
  name: descheduler
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: docker.io/shkatara/kubernetes-descheduler:v1.0.0
              imagePullPolicy: IfNotPresent
              name: descheduler
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: descheduler
          serviceAccountName: descheduler
          terminationGracePeriodSeconds: 30
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 3
