name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  docker_repository: "docker.io/shkatara/kubernetes-descheduler"
  docker_image_tag: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.docker_repository }}:${{ env.docker_image_tag }}

      - name: Push the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ env.docker_repository }}:${{ env.docker_image_tag }}
